# -*- coding: utf-8 -*-
"""ML Python Basics

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lDy3iABEgvwfRXkAG3xhmQN2LwmE7ibd
"""

length = float(input("Enter Length: "))
width = float(input("Enter width: "))
area = length * width
print("Area of Rectangle: " , area)

num = int(input("Enter a Number: "))
if num%2 == 0:
   print("Even")
else:
   print("Odd")

for i in range(1, 101):
    print (i)

num = int(input("Enter a Number:"))
factorial = 1
if num < 0:
  print("Doesn't Exist")

elif num == 0:
  print("Factorial is = 1")

else:
  for i in range(1, num + 1):
      factorial *= i
      print("Factorial : " , factorial)

num = int(input("Enter a Number:"))
reverse = 0
while num > 0:
      digit = num % 10
      reverse = reverse * 10 + digit
      num = num // 10
print("Reversed Number: " , reverse)

def is_prime(num):
    if num <= 1:
        return False

    for i in range(2, int(num ** 0.5) + 1):
      if num % i == 0:
          return False

    return True

number = int(input("Enter a Number: "))

if is_prime(number):
  print(number, " is a Prime Number")

else:
  print(number, " Is not a Prime Number")